# Generated by Django 4.0.3 on 2022-04-22 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_profile', to='web.workshop'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_profile', to='web.wifi'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='ide',
            field=models.CharField(choices=[('1', 'Arduino IDE'), ('2', 'PlatformIO'), ('2', 'Other')], default='1', max_length=1),
        ),
    ]
