# Generated by Django 4.0.3 on 2022-04-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_workshop_alter_profile_wifi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifi',
            old_name='password',
            new_name='password_w',
        ),
    ]
