# Generated by Django 4.0.3 on 2022-04-25 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_password_wifi_password_w'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifi',
            name='user',
        ),
        migrations.AddField(
            model_name='wifi',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wifis', to='web.profile'),
            preserve_default=False,
        ),
    ]
