# Generated by Django 4.0.3 on 2022-04-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_remove_wifi_user_wifi_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifi',
            old_name='password_w',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='wifi',
            name='profile',
        ),
        migrations.AddField(
            model_name='wifi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
