# Generated by Django 4.0.3 on 2022-04-28 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_rename_password_w_wifi_password_remove_wifi_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wifi',
            new_name='Wifie',
        ),
        migrations.RenameField(
            model_name='wifie',
            old_name='password',
            new_name='passworde',
        ),
    ]
