# Generated by Django 4.0.3 on 2022-04-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_wifi_wifie_rename_password_wifie_passworde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifie',
            old_name='ssid',
            new_name='sside',
        ),
    ]
