# Generated by Django 4.0.3 on 2022-04-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_ssid_wifie_sside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifie',
            old_name='sside',
            new_name='ssid',
        ),
    ]
