# Generated by Django 4.0.3 on 2022-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_sside_wifie_ssid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='signal',
            new_name='is_fixed',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='ssid',
            new_name='wifi',
        ),
        migrations.AddField(
            model_name='workshop',
            name='actname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='response',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='turn_default_in_sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='hardware',
            field=models.CharField(blank=True, choices=[('1', 'NodeMCU'), ('2', 'ESP8266')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='ide',
            field=models.CharField(blank=True, choices=[('1', 'Arduino IDE'), ('2', 'PlatformIO'), ('2', 'Other')], default='1', max_length=1, null=True),
        ),
    ]
