# Generated by Django 4.0.3 on 2022-04-29 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_rename_signal_workshop_is_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifis', to=settings.AUTH_USER_MODEL),
        ),
    ]
