# Generated by Django 4.0.3 on 2022-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_wifie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='response',
            new_name='def_resp',
        ),
        migrations.AddField(
            model_name='workshop',
            name='expected_resp',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
