# Generated by Django 4.0.3 on 2022-04-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_response_workshop_def_resp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='wifie',
            options={'verbose_name': 'Wifi', 'verbose_name_plural': 'Wifies'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='turn_default_in_sec',
        ),
        migrations.AddField(
            model_name='workshop',
            name='duration',
            field=models.IntegerField(default=0, help_text='turns default in seconds'),
        ),
    ]
