# Generated by Django 4.0.3 on 2022-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_profile_options_alter_wifie_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='secret_key',
            field=models.CharField(max_length=25),
        ),
    ]
