# Generated by Django 4.0.3 on 2022-04-30 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0013_alter_workshop_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to=settings.AUTH_USER_MODEL),
        ),
    ]
