# Generated by Django 4.0.3 on 2022-04-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_workshop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
