# Generated by Django 4.0.3 on 2022-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_workshop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='current_resp',
            field=models.CharField(blank=True, default=models.CharField(max_length=150), max_length=150, null=True),
        ),
    ]
