# Generated by Django 4.0.3 on 2022-05-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_workshop_current_resp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='current_resp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
