# Generated by Django 4.0.3 on 2022-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_workshop_current_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
