# Generated by Django 4.0.3 on 2022-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_workshop_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='button_color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('dark', 'dark')], default='primary', max_length=10),
        ),
    ]
