# Generated by Django 4.0.3 on 2022-05-16 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0020_workshop_last_action_worksop_usage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worksop_usage',
            new_name='Workshop_usage',
        ),
    ]
