# Generated by Django 4.0.3 on 2022-05-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_rename_worksop_usage_workshop_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='last_action',
            new_name='last_used',
        ),
    ]
