# Generated by Django 4.0.3 on 2022-05-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_last_action_workshop_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='button_color',
            field=models.CharField(choices=[('btn-success', 'primary'), ('btn-outline-success', 'primary-outline'), ('btn-gradiend-success', 'primary-gradient'), ('btn-danger', 'danger'), ('btn-outline-danger', 'danger-outline'), ('btn-gradient-danger', 'danger-gradient'), ('btn-dark', 'dark'), ('btn-outline-dark', 'dark-outline'), ('btn-gradient-dark', 'dark-gradient'), ('btn-light', 'light'), ('btn-outline-light', 'light-outline'), ('btn-white', 'white'), ('btn-outline-white', 'white-outline'), ('btn-gradient-white', 'white-gradient'), ('btn-secondary', 'secondary'), ('btn-outline-secondary', 'secondary-outline'), ('btn-gradient-secondary', 'secondary-gradient'), ('btn-warning', 'warning'), ('btn-outline-warning', 'warning-outline'), ('btn-gradient-warning', 'warning-gradient'), ('btn-info', 'info'), ('btn-outline-info', 'info-outline'), ('btn-gradient-info', 'info-gradient')], default='primary', max_length=30),
        ),
    ]
