# Generated by Django 4.0.3 on 2022-05-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0023_alter_workshop_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='button_color',
            field=models.CharField(choices=[('btn-outline-success', 'primary-outline'), ('btn-gradient-success', 'primary-gradient'), ('btn-danger', 'danger'), ('btn-outline-danger', 'danger-outline'), ('btn-gradient-danger', 'danger-gradient'), ('btn-dark', 'dark'), ('btn-outline-dark', 'dark-outline'), ('btn-gradient-dark', 'dark-gradient'), ('btn-light', 'light'), ('btn-secondary', 'secondary'), ('btn-outline-secondary', 'secondary-outline'), ('btn-gradient-secondary', 'secondary-gradient'), ('btn-warning', 'warning'), ('btn-outline-warning', 'warning-outline'), ('btn-gradient-warning', 'warning-gradient'), ('btn-info', 'info'), ('btn-outline-info', 'info-outline'), ('btn-gradient-info', 'info-gradient')], default='btn-danger', max_length=30),
        ),
        migrations.CreateModel(
            name='UserMovementTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=150)),
                ('browser', models.CharField(max_length=100)),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=150, null=True)),
                ('device_version', models.CharField(max_length=100)),
                ('device_model', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
