# Generated by Django 4.0.3 on 2022-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_usermovementtrack_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovementtrack',
            name='device_type',
        ),
        migrations.AddField(
            model_name='usermovementtrack',
            name='is_bot',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermovementtrack',
            name='is_mobile',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermovementtrack',
            name='is_pc',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermovementtrack',
            name='is_tablet',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
