# Generated by Django 4.0.3 on 2022-06-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_remove_usermovementtrack_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovementtrack',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='usermovementtrack',
            name='device_version',
        ),
        migrations.RemoveField(
            model_name='usermovementtrack',
            name='screen',
        ),
    ]
