# Generated by Django 4.0.3 on 2022-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_usermovementtrack_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='detail_url',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
