# Generated by Django 4.0.3 on 2022-06-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_workshop_detail_url_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
