# Generated by Django 4.0.3 on 2022-06-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0031_delete_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop_actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('1', 'Added'), ('2', 'Used'), ('3', 'Removed')], max_length=30)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_actions', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='web.workshop')),
            ],
            options={
                'verbose_name': 'Workshop usage',
                'verbose_name_plural': 'Workshop usages',
            },
        ),
        migrations.DeleteModel(
            name='Workshop_usage',
        ),
    ]
