# Generated by Django 4.0.3 on 2022-06-11 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0032_workshop_actions_delete_workshop_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_actions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workshop_actions',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='web.workshop'),
        ),
    ]
