# Generated by Django 4.0.3 on 2022-06-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0033_alter_workshop_actions_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_actions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workshop_actions',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='web.workshop'),
        ),
    ]
