# Generated by Django 4.0.3 on 2022-06-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0035_alter_workshop_actions_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermovementtrack',
            options={'verbose_name': 'User Track', 'verbose_name_plural': 'User Tracks'},
        ),
        migrations.CreateModel(
            name='HitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
