# Generated by Django 4.0.3 on 2022-06-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0036_alter_usermovementtrack_options_hitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreenWorkshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homescreen_workshops', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.workshop')),
            ],
            options={
                'verbose_name': 'HomeScreen Workshop',
                'verbose_name_plural': 'HomeScreen Workshops',
            },
        ),
    ]
